name: flutter_core
description: "A new Flutter project."
version: 0.0.1

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  my_localizations:
    git:
      url: https://github.com/vraj0703/my_localizations.git
  my_logger_metrics:
    git:
      url: https://github.com/vraj0703/my_logger_metrics.git

  web: ^1.0.0
  get_it: ^9.1.0
  plugin_platform_interface: ^2.0.2
  internet_connection_checker: ^3.0.1
  dart_either: ^2.0.0
  shared_preferences: ^2.5.3
  graphql_flutter: ^5.2.1
  intl: ^0.20.2
  freezed_annotation: ^3.1.0
  json_annotation: ^4.7.0
  injectable: ^2.1.1
  timezone: ^0.10.1
  path_provider: ^2.1.5
  collection: ^1.19.1
  http: ^1.2.1
  home_widget: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  injectable_generator: ^2.1.1
  freezed: ^3.2.3
  build_runner: ^2.3.3
  mockito: ^5.5.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.example.flutter_core
        pluginClass: FlutterCorePlugin
      ios:
        pluginClass: FlutterCorePlugin
      linux:
        pluginClass: FlutterCorePlugin
      macos:
        pluginClass: FlutterCorePlugin
      windows:
        pluginClass: FlutterCorePluginCApi
      web:
        pluginClass: FlutterCoreWeb
        fileName: flutter_core_web.dart

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
